import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {},

  upBackground: {
    height: 130,
    backgroundColor: "#02AFEF",
  },
  centerBackground: {
    flex: 1,
    top: -2,
    height: 165,
    backgroundColor: "#02AFEF",
    borderBottomRightRadius: 85,
  },
  textUpBackground: {
    top: 95,
    left: 15,
    color: "#FFFFFF",
    fontSize: 22,
    fontWeight: "400",
  },
  iconsUpBackground1: {
    right: -300,
    top: 70,
    color: "#FFFFFF",
  },
  iconsUpBackground2: {
    right: -355,
    top: 48,
    color: "#FFFFFF",
  },
  downBackground: {
    flex: 1,
    backgroundColor: "#F1F4F8",
  },
  containerCaixas: {
    flex: 1,
    gap: 20,
    alignItems: "center",
  },
  box1: {
    flex: 1,
    top: -150,
    width: 360,
    height: 390,
    backgroundColor: "#FFFFFF",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 1,
    borderRadius: 5,
    zIndex: 1,
  },
  box2: {
    flex: 1,
    top: -150,
    width: 360,
    height: 310,
    backgroundColor: "white",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 1,
    borderRadius: 5,
  },
  box3: {
    flex: 1,
    top: -150,
    width: 365,
    height: 500,
    backgroundColor: "white",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 1,
    borderRadius: 5,
  },
  box4: {
    flex: 1,
    top: -150,
    width: 365,
    height: 120,
    backgroundColor: "white",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 1,
    borderRadius: 5,
  },
  box5: {
    flex: 1,
    top: -150,
    width: 365,
    height: 180,
    backgroundColor: "white",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 1,
    borderRadius: 5,
  },

  textBox1: {
    top: 38,
    left: 20,
    fontSize: 21,
    fontWeight: "500",
    letterSpacing: 0.9,
  },

  textBox2: {
    top: -100,
    left: 20,
    fontSize: 21,
    fontWeight: "600",
    letterSpacing: 0.9,
  },
  textBox22: {
    top: -100,
    left: 20,
    fontSize: 14,
    fontWeight: "300",
    letterSpacing: 0.9,
  },
  textBox3: {
    top: -112,
    left: 20,
    fontSize: 21,
    fontWeight: "600",
    letterSpacing: 0.9,
  },
  textBox4: {
    top: -160,
    left: 20,
    fontSize: 19,
    fontWeight: "bold",
    letterSpacing: 0.9,
  },
  textBox5: {
    top: -5,
    marginLeft: "35%",
    fontSize: 14,
    fontWeight: "bold",
    letterSpacing: 0.5,
    color: "#1A69C7",
  },
  saldo1: {
    top: -10,
    marginLeft: 90,
    fontSize: 17,
    letterSpacing: 0.5,
  },
  saldo2: {
    top: -10,
    marginLeft: 90,
    fontSize: 19,
    letterSpacing: 0.5,
    fontWeight: "bold",
  },
  saldo3: {
    top: -52,
    marginLeft: 90,
    fontSize: 17,
    letterSpacing: 0.5,
  },
  saldo4: {
    top: -52,
    marginLeft: 90,
    fontSize: 19,
    fontWeight: "bold",
    letterSpacing: 0.5,
  },
  saldo5: {
    top: -85,
    marginLeft: 90,
    fontSize: 17,
    letterSpacing: 0.5,
  },
  saldo6: {
    top: -85,
    marginLeft: 90,
    fontSize: 19,
    fontWeight: "bold",
    letterSpacing: 0.5,
  },
  saldo10: {
    top: -40,
    color: "#1A69C7",
    textAlign: "center",
    fontSize: 16,
    fontWeight: "bold",
    letterSpacing: 0.7,
  },
  saldo1Icone1: {
    marginLeft: 44,
    top: 80,
    zIndex: 1,
  },
  saldo1Icone2: {
    marginLeft: 38,
    top: 42,
    zIndex: 1,
  },
  saldo1Icone3: {
    marginLeft: 38,
    top: 5,
    zIndex: 1,
  },
  saldo1IconeBox1: {
    backgroundColor: "#F1F4F8",
    top: 40,
    marginLeft: 23,
    width: 55,
    height: 55,
    borderRadius: 10,
  },
  saldo1IconeBox2: {
    backgroundColor: "#F1F4F8",
    top: 1,
    marginLeft: 23,
    width: 55,
    height: 55,
    borderRadius: 10,
  },
  saldo1IconeBox3: {
    backgroundColor: "#F1F4F8",
    top: -35,
    marginLeft: 23,
    width: 55,
    height: 55,
    borderRadius: 10,
  },
  barraVerde: {
    position: "absolute",
    width: 7,
    height: 65,
    top: 95,
    backgroundColor: "green",
    borderTopEndRadius: 5,
    borderBottomEndRadius: 5,
  },
  barraVermelha: {
    position: "absolute",
    width: 7,
    height: 65,
    top: 185,
    backgroundColor: "red",
    borderTopEndRadius: 5,
    borderBottomEndRadius: 5,
  },
  pagamentos: {
    flexDirection: "row",
    top: 30,
    marginLeft: 20,
    justifyContent: "flex-start",
    gap: 120,
  },
  recebimentos: {
    flexDirection: "row",
    top: -40,
    marginLeft: 20,
    justifyContent: "flex-start",
    gap: 100,
  },
  textRecebimentos: {
    fontSize: 16,
    letterSpacing: 0.5,
  },
  textPagamentos: {
    fontSize: 16,
    letterSpacing: 0.5,
  },
  textMoney: {
    fontWeight: "bold",
    fontSize: 16,
    letterSpacing: 0.5,
  },

  textBox33: {
    top: -110,
    left: 20,
    fontSize: 14,
    fontWeight: "300",
    letterSpacing: 0.9,
  },

  textMaisDetalhes: {
    top: 100,
    color: "#1A69C7",
    textAlign: "center",
    fontSize: 17,
    fontWeight: "bold",
    letterSpacing: 0.7,
  },
  barraVermelha1: {
    position: "absolute",
    width: 7,
    height: 65,
    top: 350,
    backgroundColor: "red",
    borderTopEndRadius: 5,
    borderBottomEndRadius: 5,
  },
  barraVerde1: {
    position: "absolute",
    width: 7,
    height: 65,
    top: 270,
    backgroundColor: "green",
    borderTopEndRadius: 5,
    borderBottomEndRadius: 5,
  },
  barraAmarela: {
    position: "absolute",
    width: 7,
    height: 65,
    top: 190,
    backgroundColor: "#FFC958",
    borderTopEndRadius: 5,
    borderBottomEndRadius: 5,
  },
  barraAzul: {
    position: "absolute",
    width: 7,
    height: 65,
    top: 110,
    backgroundColor: "#43A2D9",
    borderTopEndRadius: 5,
    borderBottomEndRadius: 5,
  },
  barrasRecusados: {
    flexDirection: "row",
    top: 65,
    marginLeft: 20,
    justifyContent: "flex-start",
    gap: 120,
  },
  barrasOrcamentos: {
    flexDirection: "row",
    top: -8,
    marginLeft: 20,
    justifyContent: "flex-start",
    gap: 115,
  },
  barrasAceitos: {
    flexDirection: "row",
    top: 30,
    marginLeft: 20,
    justifyContent: "flex-start",
    gap: 150,
  },
  barrasVendas: {
    flexDirection: "row",
    top: -50,
    marginLeft: 20,
    justifyContent: "flex-start",
    gap: 150,
  },
  textRecusados1: {
    top: 33,
    fontSize: 16,
    letterSpacing: 0.5,
    marginLeft: 20,
  },
  textRecusados2: {
    top: 10,
    fontSize: 16,
    letterSpacing: 0.5,
  },
  textAceitos1: {
    top: 0,
    fontSize: 16,
    letterSpacing: 0.5,
    marginLeft: 20,
  },
  textAceitos2: {
    fontSize: 16,
    letterSpacing: 0.5,
    top: 10,
  },
  textOrcamentos1: {
    top: -40,
    fontSize: 16,
    letterSpacing: 0.5,
    marginLeft: 20,
  },
  textOrcamentos2: {
    fontSize: 16,
    letterSpacing: 0.5,
    top: 10,
  },
  textVendas1: {
    top: -80,
    fontSize: 16,
    letterSpacing: 0.5,
    marginLeft: 20,
  },
  textVendas2: {
    fontSize: 16,
    letterSpacing: 0.5,
    top: 10,
  },

  textMoney1: {
    fontWeight: "bold",
    letterSpacing: 0.7,
    fontSize: 19,
  },
  textMoney2: {
    fontWeight: "bold",
    letterSpacing: 0.7,
    fontSize: 19,
  },

  textMoney3: {
    fontWeight: "bold",
    letterSpacing: 0.7,
    fontSize: 19,
  },
  text1Box4: {
    left: 20,
    fontSize: 24,
    fontWeight: "bold",
    letterSpacing: 0.9,
  },
  text2Box4: {
    top: 5,
    left: 20,
    fontSize: 14,
    fontWeight: "300",
    letterSpacing: 0.9,
  },
  box4Icone1: {
    position: "absolute",
    top: -50,
    right: 6,
  },
  textFinal: {
    marginLeft: "35%",
  },
  textFinal1: {
    color: "#1A69C7",
    fontSize: 12,
    letterSpacing: 0.5,
  },
  contentImage: {
    position: "absolute",
    top: 45,
    marginLeft: 20,
  },
});

export default styles;
